let lerum =
  {
  id: '1',
  title: 'my first note',
  folder: 'root',
  timestamp: '1',
  content: `
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
orem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vestibulum in augue ac dapibus. Cras turpis mauris, tempus a varius quis, sollicitudin vel metus. Quisque venenatis nibh est, volutpat facilisis nisi molestie vel. Nullam tincidunt elementum purus a rutrum. Integer a mi rutrum, efficitur augue at, ultrices justo. Vestibulum vel gravida purus. Curabitur et nulla sed magna condimentum malesuada. Etiam ut lacus velit. Fusce sed dapibus eros.

Quisque et ipsum nisl. Phasellus eros turpis, finibus lobortis eleifend sit amet, interdum id eros. Morbi augue est, cursus ac rhoncus vitae, accumsan sit amet mi. Nulla gravida pellentesque orci non sollicitudin. Curabitur eget urna quis augue porta efficitur sed quis turpis. Vestibulum blandit ipsum dui, vitae pellentesque velit mattis sit amet. Ut sodales mi ex, at aliquet mauris sollicitudin at. Integer luctus lectus vel diam iaculis vehicula.

Maecenas commodo, ligula in luctus lobortis, dolor lacus pulvinar ligula, ac tempus lorem nisl ut sapien. In vestibulum lacinia quam quis dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae commodo ipsum. Morbi quis quam purus. In a malesuada enim. Curabitur faucibus purus eget mollis porta. Suspendisse efficitur sed nunc id aliquet.
  `
  };

module.exports = {
  lerum: lerum
};